model_access_dict = {
    'model': {
        'read': 'Read',
        'create': 'Create',
        'update': 'Update',
        'delete': 'Delete',
        'search': {'name': 'Search', 'relation': 'read'},
        'related_read': {'name': 'Related read', 'relation': 'read'},
        'get_defaults': {'name': 'Get defaults', 'relation': 'read'},
    },
    'size': {
        'read': 'Read',
        'create': 'Create',
        'update': 'Update',
        'delete': 'Delete',
        'search': {'name': 'Search', 'relation': 'read'},
        'related_read': {'name': 'Related read', 'relation': 'read'},
        'get_defaults': {'name': 'Get defaults', 'relation': 'read'},
    },
    'model_item': {
        'read': 'Read',
        'create': 'Create',
        'update': 'Update',
        'delete': 'Delete',
        'search': {'name': 'Search', 'relation': 'read'},
        'related_read': {'name': 'Related read', 'relation': 'read'},
        'get_defaults': {'name': 'Get defaults', 'relation': 'read'},
    },
    'order': {
        'read': 'Read',
        'create': 'Create',
        'update': 'Update',
        'delete': 'Delete',
        'search': {'name': 'Search', 'relation': 'read'},
        'related_read': {'name': 'Related read', 'relation': 'read'},
        'get_defaults': {'name': 'Get defaults', 'relation': 'read'},
        'upload_order_to_gdrive': 'Upload to Gdrive',
        'copy_cred_file': {'name': 'Copy Google credentials', 'relation': 'upload_order_to_gdrive'},
        'update_status': {'name': 'Update status', 'relation': 'update'},
    },
    'order_item': {
        'read': 'Read',
        'create': 'Create',
        'update': 'Update',
        'delete': 'Delete',
        'search': {'name': 'Search', 'relation': 'read'},
        '_onchange_model': {'name': 'Model Change', 'relation': 'read'},
        'related_read': {'name': 'Related read', 'relation': 'read'},
        'get_defaults': {'name': 'Get defaults', 'relation': 'read'},
        'update_status': {'name': 'Update status', 'relation': 'update'},
    },
    'pallet': {
        'read': 'Read',
        'create': 'Create',
        'update': 'Update',
        'delete': 'Delete',
        'search': {'name': 'Search', 'relation': 'read'},
        'related_read': {'name': 'Related read', 'relation': 'read'},
        'get_defaults': {'name': 'Get defaults', 'relation': 'read'},

    },
    'part': {
        'read': 'Read',
        'create': 'Create',
        'update': 'Update',
        'delete': 'Delete',
        'search': {'name': 'Search', 'relation': 'read'},
        'related_read': {'name': 'Related read', 'relation': 'read'},
        'get_defaults': {'name': 'Get defaults', 'relation': 'read'},
        '_side_selection': {'name': 'Side selection', 'relation': 'read'}
    },
    'box': {
        'read': 'Read',
        'create': 'Create',
        'update': 'Update',
        'delete': 'Delete',
        'search': {'name': 'Search', 'relation': 'read'},
        'related_read': {'name': 'Related read', 'relation': 'read'},
        'get_defaults': {'name': 'Get defaults', 'relation': 'read'},
        'update_status': {'name': 'Update status', 'relation': 'update'},
    },
    'item_set': {
        'read': 'Read',
        'create': 'Create',
        'update': 'Update',
        'delete': 'Delete',
        'search': {'name': 'Search', 'relation': 'read'},
        'related_read': {'name': 'Related read', 'relation': 'read'},
        'get_defaults': {'name': 'Get defaults', 'relation': 'read'},
        'update_status': {'name': 'Update status', 'relation': 'update'},
    },
    'app_setting': {
        'read': 'Read',
        'create': 'Create',
        'update': 'Update',
        'get_setting': {'name': 'Get app setting', 'relation': 'read'},
        'search': {'name': 'Search', 'relation': 'read'},
        'related_read': {'name': 'Related read', 'relation': 'read'},
        'get_defaults': {'name': 'Get defaults', 'relation': 'read'}, 
    },
    'admin_setting': {
        'read': 'Read',
        'create': 'Create',
        'update': 'Update',
        'get_setting': {'name': 'Get app setting', 'relation': 'read'},
        'search': {'name': 'Search', 'relation': 'read'},
        'related_read': {'name': 'Related read', 'relation': 'read'},
        'get_defaults': {'name': 'Get defaults', 'relation': 'read'},
        'master_pass_check': {'name': 'Master password check', 'relation': 'read'},
    },
    'user_setting': {
        'read': 'Read',
        'create': 'Create',
        'update': 'Update',
        'get_setting': {'name': 'Get user setting', 'relation': 'read'},
        'search': {'name': 'Search', 'relation': 'read'},
        'related_read': {'name': 'Related read', 'relation': 'read'},
        'get_defaults': {'name': 'Get defaults', 'relation': 'read'},
        '_theme_selection': {'name': 'Theme selection', 'relation': 'read'},
        '_camera_selection': {'name': 'Camera selection', 'relation': 'read'},
    },
    'parts_per_box_report': {
        'read': 'Read',
        'search': {'name': 'Search', 'relation': 'read'},
        'related_read': {'name': 'Related read', 'relation': 'read'},
        'get_defaults': {'name': 'Get defaults', 'relation': 'read'},
        '_side_selection': {'name': 'Side selection', 'relation': 'read'},
    },
    'parts_per_order_report': {
        'read': 'Read',
        'search': {'name': 'Search', 'relation': 'read'},
        'related_read': {'name': 'Related read', 'relation': 'read'},
        'get_defaults': {'name': 'Get defaults', 'relation': 'read'},
        '_side_selection': {'name': 'Side selection', 'relation': 'read'},
    },
    'all_orders_general_report': {
        'read': 'Read',
        'search': {'name': 'Search', 'relation': 'read'},
        'related_read': {'name': 'Related read', 'relation': 'read'},
        'get_defaults': {'name': 'Get defaults', 'relation': 'read'},
        '_side_selection': {'name': 'Side selection', 'relation': 'read'},
    },
    'caption_set': {
        'read': 'Read',
        'create': 'Create',
        'update': 'Update',
        'delete': 'Delete',
        'search': {'name': 'Search', 'relation': 'read'},
        'related_read': {'name': 'Related read', 'relation': 'read'},
        'get_defaults': {'name': 'Get defaults', 'relation': 'read'},
    },
}


view_access_dict = {
    'UiOrderForm': {
        'list': 'List view',
        'form': 'Detail view',
        'create': 'Create',
        'update': 'Update',
        'delete': 'Delete',
        'upload_order_to_gdrive': 'upload_order_to_gdrive',
    },
    'UiOrderItemForm': {
        'list': 'List view',
        'form': 'Detail view',
        'create': 'Create',
        'update': 'Update',
        'delete': 'Delete',
    },
    'UiModelForm': {
        'list': 'List view',
        'form': 'Detail view',
        'create': 'Create',
        'update': 'Update',
        'delete': 'Delete',
    },
    'UiSizeForm': {
        'list': 'List view',
        'form': 'Detail view',
        'create': 'Create',
        'update': 'Update',
        'delete': 'Delete',
    },
    'UiModelItemForm': {
        'list': 'List view',
        'form': 'Detail view',
        'create': 'Create',
        'update': 'Update',
        'delete': 'Delete',
    },
    'UiBoxForm': {
        'list': 'List view',
        'form': 'Detail view',
        'create': 'Create',
        'update': 'Update',
        'delete': 'Delete',
    },
    'UiItemSetForm': {
        'list': 'List view',
        'form': 'Detail view',
        'create': 'Create',
        'update': 'Update',
        'delete': 'Delete',
    },
    'UiPalletForm': {
        'list': 'List view',
        'form': 'Detail view',
        'create': 'Create',
        'update': 'Update',
        'delete': 'Delete',
    },
    'UiPartForm': {
        'list': 'List view',
        'form': 'Detail view',
        'create': 'Create',
        'update': 'Update',
        'delete': 'Delete',
    },
    'UiPartsPerBoxReportForm': {
        'list': 'List view',
    },
    'UiPartsPerOrderReportForm': {
        'list': 'List view',
    },
    'UiAllOrdersGeneralReportForm': {
        'list': 'List view',
    },
    'UiAppSettingForm': {
        'list': 'List view',
        'form': 'Detail view',
        'create': 'Create',
        'update': 'Update',
    },
    'UiUserSettingForm': {
        'list': 'List view',
        'form': 'Detail view',
        'create': 'Create',
        'update': 'Update',
    },
    'UiAdminSettingForm': {
        'list': 'List view',
        'form': 'Detail view',
        'create': 'Create',
        'update': 'Update',
    },
    'UiCaptionSetForm': {
        'list': 'List view',
        'form': 'Detail view',
        'create': 'Create',
        'update': 'Update',
    },
}
