# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frameForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtCore import *


class BaseFrameForm(QMainWindow):
    def setupUi(self, BaseFrameForm):
        
        if not BaseFrameForm.objectName():
            BaseFrameForm.setObjectName(u"BaseFrameForm")
        BaseFrameForm.resize(557, 300)
        font = QFont()
        font.setPointSize(8)
        BaseFrameForm.setFont(font)
        BaseFrameForm.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        BaseFrameForm.actionClasses = QAction(BaseFrameForm)
        BaseFrameForm.actionClasses.setObjectName(u"actionClasses")
        BaseFrameForm.actionTags = QAction(BaseFrameForm)
        BaseFrameForm.actionTags.setObjectName(u"actionTags")
        BaseFrameForm.actionExit = QAction(BaseFrameForm)
        BaseFrameForm.actionExit.setObjectName(u"actionExit")
        BaseFrameForm.actionProfiles = QAction(BaseFrameForm)
        BaseFrameForm.actionProfiles.setObjectName(u"actionProfiles")
        BaseFrameForm.actionAboutUs = QAction(BaseFrameForm)
        BaseFrameForm.actionAboutUs.setObjectName(u"actionAboutUs")
        BaseFrameForm.actionSetting = QAction(BaseFrameForm)
        BaseFrameForm.actionSetting.setObjectName(u"actionSetting")
        BaseFrameForm.actionDescriptions = QAction(BaseFrameForm)
        BaseFrameForm.actionDescriptions.setObjectName(u"actionDescriptions")
        BaseFrameForm.actionReport = QAction(BaseFrameForm)
        BaseFrameForm.actionReport.setObjectName(u"actionReport")
        BaseFrameForm.actionUsers = QAction(BaseFrameForm)
        BaseFrameForm.actionUsers.setObjectName(u"actionUsers")
        BaseFrameForm.centralwidget = QWidget(BaseFrameForm)
        BaseFrameForm.centralwidget.setObjectName(u"centralwidget")
        BaseFrameForm.gridLayout = QGridLayout(BaseFrameForm.centralwidget)
        BaseFrameForm.gridLayout.setObjectName(u"gridLayout")
        BaseFrameForm.navigationMainWidget = QWidget(BaseFrameForm.centralwidget)
        BaseFrameForm.navigationMainWidget.setObjectName(u"navigationMainWidget")
        BaseFrameForm.gridLayout_3 = QGridLayout(BaseFrameForm.navigationMainWidget)
        BaseFrameForm.gridLayout_3.setObjectName(u"gridLayout_3")
        BaseFrameForm.navigationBarWidget = QWidget(BaseFrameForm.navigationMainWidget)
        BaseFrameForm.navigationBarWidget.setObjectName(u"navigationBarWidget")
        sizePolicy1 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(BaseFrameForm.navigationBarWidget.sizePolicy().hasHeightForWidth())
        BaseFrameForm.navigationBarWidget.setSizePolicy(sizePolicy1)
        BaseFrameForm.horizontalLayout = QHBoxLayout(BaseFrameForm.navigationBarWidget)
        BaseFrameForm.horizontalLayout.setObjectName(u"horizontalLayout")
        BaseFrameForm.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        # BaseFrameForm.navPushButton = QPushButton(BaseFrameForm.navigationBarWidget)
        # BaseFrameForm.navPushButton.setObjectName(u"navPushButton")

        # BaseFrameForm.horizontalLayout.addWidget(BaseFrameForm.navPushButton)


        BaseFrameForm.gridLayout_3.addWidget(BaseFrameForm.navigationBarWidget, 0, 0, 1, 1)

        BaseFrameForm.horizontalSpacer = QSpacerItem(3000, 20, QSizePolicy.Preferred, QSizePolicy.Preferred)

        BaseFrameForm.gridLayout_3.addItem(BaseFrameForm.horizontalSpacer, 0, 1, 1, 1)

        BaseFrameForm.navigationButtonsWidget = QWidget(BaseFrameForm.navigationMainWidget)
        BaseFrameForm.navigationButtonsWidget.setObjectName(u"navigationButtonsWidget")
        BaseFrameForm.gridLayout_4 = QGridLayout(BaseFrameForm.navigationButtonsWidget)
        BaseFrameForm.gridLayout_4.setObjectName(u"gridLayout_4")
        BaseFrameForm.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        BaseFrameForm.backPushButton = QPushButton(BaseFrameForm.navigationButtonsWidget)
        BaseFrameForm.backPushButton.setObjectName(u"backPushButton")

        BaseFrameForm.gridLayout_4.addWidget(BaseFrameForm.backPushButton, 0, 0, 1, 1)


        BaseFrameForm.gridLayout_3.addWidget(BaseFrameForm.navigationButtonsWidget, 0, 2, 1, 1)


        BaseFrameForm.gridLayout.addWidget(BaseFrameForm.navigationMainWidget, 0, 0, 1, 1)

        BaseFrameForm.stackMainWidget = QWidget(BaseFrameForm.centralwidget)
        BaseFrameForm.stackMainWidget.setObjectName(u"stackMainWidget")
        BaseFrameForm.gridLayout_2 = QGridLayout(BaseFrameForm.stackMainWidget)
        BaseFrameForm.gridLayout_2.setSpacing(0)
        BaseFrameForm.gridLayout_2.setObjectName(u"gridLayout_2")
        BaseFrameForm.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        BaseFrameForm.stackedWidget = QStackedWidget(BaseFrameForm.stackMainWidget)
        BaseFrameForm.stackedWidget.setObjectName(u"stackedWidget")

        BaseFrameForm.gridLayout_2.addWidget(BaseFrameForm.stackedWidget, 0, 0, 1, 1)


        BaseFrameForm.gridLayout.addWidget(BaseFrameForm.stackMainWidget, 1, 0, 1, 1)

        BaseFrameForm.setCentralWidget(BaseFrameForm.centralwidget)
        BaseFrameForm.statusBar = QStatusBar(BaseFrameForm)
        BaseFrameForm.statusBar.setObjectName(u"statusBar")
        BaseFrameForm.setStatusBar(BaseFrameForm.statusBar)
        BaseFrameForm.menuBar = QMenuBar(BaseFrameForm)
        BaseFrameForm.menuBar.setObjectName(u"menuBar")
        BaseFrameForm.menuBar.setGeometry(QRect(0, 0, 557, 19))
        BaseFrameForm.setMenuBar(BaseFrameForm.menuBar)

        self.retranslateUi(BaseFrameForm)

        BaseFrameForm.stackedWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(BaseFrameForm)

    def retranslateUi(self, BaseFrameForm):
        _translate = QtCore.QCoreApplication.translate
        BaseFrameForm.actionClasses.setText(_translate("BaseFrameForm", "مدیریت دسته ها"))
        BaseFrameForm.actionTags.setText(_translate("BaseFrameForm", "مدیریت تگ ها"))
        BaseFrameForm.actionExit.setText(_translate("BaseFrameForm", "خروج"))
        BaseFrameForm.actionProfiles.setText(_translate("BaseFrameForm", "پروفایل ها"))
        BaseFrameForm.actionAboutUs.setText(_translate("BaseFrameForm", "درباره ما"))
        BaseFrameForm.actionSetting.setText(_translate("BaseFrameForm", "تنظیمات"))
        BaseFrameForm.actionDescriptions.setText(_translate("BaseFrameForm", "مدیریت کپشن ها"))
        BaseFrameForm.actionReport.setText(_translate("BaseFrameForm", "گزارش"))
        BaseFrameForm.actionUsers.setText(_translate("BaseFrameForm", "مدیریت کاربران"))
