# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'baseFormListLayoutForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class BaseFormListLayoutForm(object):
    def setupUi(self, baseFormListLayoutForm):
        baseFormListLayoutForm.setObjectName("baseFormListLayoutForm")
        baseFormListLayoutForm.resize(543, 259)
        baseFormListLayoutForm.formListGridLayout = QtWidgets.QGridLayout(baseFormListLayoutForm)
        baseFormListLayoutForm.formListGridLayout.setContentsMargins(0, 0, 0, 0)
        baseFormListLayoutForm.formListGridLayout.setSpacing(0)
        baseFormListLayoutForm.formListGridLayout.setObjectName("formListGridLayout")
        baseFormListLayoutForm.baseFormListLayoutWidget = QtWidgets.QWidget(baseFormListLayoutForm)
        baseFormListLayoutForm.baseFormListLayoutWidget.setObjectName("baseFormListLayoutWidget")
        baseFormListLayoutForm.formListGridLayout.addWidget(baseFormListLayoutForm.baseFormListLayoutWidget, 0, 0, 1, 1)
        
        baseFormListLayoutForm.baseFormListLayoutWidgetLayout = QtWidgets.QGridLayout(baseFormListLayoutForm.baseFormListLayoutWidget)
        baseFormListLayoutForm.baseFormListLayoutWidgetLayout.setContentsMargins(0, 0, 0, 0)
        baseFormListLayoutForm.baseFormListLayoutWidgetLayout.setSpacing(0)
        baseFormListLayoutForm.baseFormListLayoutWidgetLayout.setObjectName("baseFormListLayoutWidgetLayout")
        
        self.retranslateUi(baseFormListLayoutForm)
        QtCore.QMetaObject.connectSlotsByName(baseFormListLayoutForm)

    def retranslateUi(self, baseFormListLayoutForm):
        _translate = QtCore.QCoreApplication.translate
        baseFormListLayoutForm.setWindowTitle(_translate("baseFormListLayoutForm", "Form"))
