# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'userAccessForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UserAccessForm(object):
    def setupUi(self, parent):
        parent.setObjectName("UserAccessForm")
        parent.resize(386, 455)
        parent.centralwidget = QtWidgets.QWidget(parent)
        parent.centralwidget.setObjectName("centralwidget")
        parent.gridLayout_2 = QtWidgets.QGridLayout(parent.centralwidget)
        parent.gridLayout_2.setObjectName("gridLayout_2")
        parent.groupBox = QtWidgets.QGroupBox(parent.centralwidget)
        parent.groupBox.setTitle("")
        parent.groupBox.setObjectName("groupBox")
        parent.gridLayout = QtWidgets.QGridLayout(parent.groupBox)
        parent.gridLayout.setObjectName("gridLayout")
        parent.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        parent.horizontalLayout_2.setObjectName("horizontalLayout_2")
        parent.horizontalLayout = QtWidgets.QHBoxLayout()
        parent.horizontalLayout.setObjectName("horizontalLayout")
        parent.userLabel = QtWidgets.QLabel(parent.groupBox)
        parent.userLabel.setObjectName("userLabel")
        parent.horizontalLayout.addWidget(parent.userLabel)
        parent.userLineEdit = QtWidgets.QLineEdit(parent.groupBox)
        parent.userLineEdit.setText("")
        parent.userLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        parent.userLineEdit.setReadOnly(True)
        parent.userLineEdit.setObjectName("userLineEdit")
        parent.horizontalLayout.addWidget(parent.userLineEdit)
        parent.horizontalLayout_2.addLayout(parent.horizontalLayout)
        parent.savePushButton = QtWidgets.QPushButton(parent.groupBox)
        parent.savePushButton.setObjectName("savePushButton")
        parent.horizontalLayout_2.addWidget(parent.savePushButton)
        parent.cancelPushButton = QtWidgets.QPushButton(parent.groupBox)
        parent.cancelPushButton.setObjectName("cancelPushButton")
        parent.horizontalLayout_2.addWidget(parent.cancelPushButton)
        parent.gridLayout.addLayout(parent.horizontalLayout_2, 0, 0, 1, 1)
        parent.accessListWidget = QtWidgets.QTreeWidget(parent.groupBox)
        parent.accessListWidget.setHeaderHidden(True)
        # parent.accessListWidget.setProperty("headerHidden", True)
        parent.accessListWidget.setObjectName("accessListWidget")
        parent.accessListWidget.header().setVisible(False)
        parent.gridLayout.addWidget(parent.accessListWidget, 1, 0, 1, 1)
        parent.gridLayout_2.addWidget(parent.groupBox, 0, 0, 1, 1)
        parent.setCentralWidget(parent.centralwidget)

        self.retranslateUi(parent)
        QtCore.QMetaObject.connectSlotsByName(parent)

    def retranslateUi(self, parent):
        _translate = QtCore.QCoreApplication.translate
        parent.setWindowTitle(_translate("parent", "User Access"))
        parent.userLabel.setText(_translate("parent", "User:"))
        parent.savePushButton.setText(_translate("parent", "Save"))
        parent.cancelPushButton.setText(_translate("parent", "Cancel"))
        # parent.accessListWidget.headerItem().setText(0, _translate("parent", "1"))
